baseurl: https://vocal-meringue-56335e.netlify.app # the subpath of your site, e.g. /blog
url: "https://vocal-meringue-56335e.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:title/
      
  - scope:
      path: '_pages'
    values:
      permalink: /:title/
      description: Add in a meta description for SEO.

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title/

sass:
  sass_dir: _sass
  style: compressed