#-------------------------------
# General Site Settings
title: Simple Home Mom
logo: logo1.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Kelly Briggs
  image: SHM website graphic front.jpg
  say-hello: <strong>Welcome!</strong>
  bio: Are you a <strong>stay at home mom</strong> struggling to manage your home? If so, you've come to the right place. You'll find <strong>simple home management tips</strong> here that are just for you!


#-------------------------------
# Contact links
instagram: https://instagram.com/simplehomemom # Add your Instagram handle
pinterest: https://pinterest.com/simplehomemom # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: simplehomemom # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: simplehomemom # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - 